# -*- coding: utf-8 -*-
"""Untitled16.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/14Scl2bz8KaQFJhTZf9_6FIyA6VpOwTvE
"""

# Commented out IPython magic to ensure Python compatibility.
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import pylab as pl
# %matplotlib inline

Downloading the data

!wget -O FuelConsumption.csv https://s3-api.us-geo.objectstorage.softlayer.net/cf-courses-data/CognitiveClass/ML0101ENv3/labs/FuelConsumptionCo2.csv

"""Readind the dataset"""

df=pd.read_csv('FuelConsumption.csv')
df.head()

cdf = df[['ENGINESIZE','CYLINDERS','FUELCONSUMPTION_CITY','FUELCONSUMPTION_HWY','FUELCONSUMPTION_COMB','CO2EMISSIONS']]
cdf.head(9)

"""plot engine size with emission"""

plt.scatter(cdf.ENGINESIZE, cdf.CO2EMISSIONS)
plt.xlabel('Engine Size')
plt.ylabel('Emissions')
plt.show()

"""Train Test Splits"""

msk= np.random.rand(len(df)) < 0.8
train=cdf[msk]
test=cdf[~msk]

"""Train data distribution"""

plt.scatter(train.ENGINESIZE, train.CO2EMISSIONS)
plt.xlabel('Engine Size')
plt.ylabel('Emission')
plt.show()

"""Multiple Linear Regression"""

from sklearn import linear_model
regr=linear_model.LinearRegression()
x= np.asanyarray(train[['ENGINESIZE','CYLINDERS','FUELCONSUMPTION_CITY','FUELCONSUMPTION_HWY','FUELCONSUMPTION_COMB']])
y=np.asanyarray(train[['CO2EMISSIONS']])
regr.fit(x,y)
print("regression coefficeints", regr.coef_)

"""Prediction"""

yhat = regr.predict(test[['ENGINESIZE','CYLINDERS','FUELCONSUMPTION_CITY','FUELCONSUMPTION_HWY','FUELCONSUMPTION_COMB']])
x = np.asanyarray(test[['ENGINESIZE','CYLINDERS','FUELCONSUMPTION_CITY','FUELCONSUMPTION_HWY','FUELCONSUMPTION_COMB']])
y= np.asanyarray(test[['CO2EMISSIONS']])
print('residual sum of squares %.2F'% np.mean((yhat - y)**2))
print('variance score %.2F'% regr.score(x,y))



